nodeLinker: node-modules
enableGlobalCache: false
nmMode: hardlinks-local
enableImmutableInstalls: false

# 启用长路径支持
enableHardenedMode: false

# 设置自定义缓存目录
cacheFolder: "./.yarn/cache"

compressionLevel: mixed

# 优化安装性能
enableProgressBars: true 