// 自动生成的内容
// 请勿手动修改此文件
export const PackageList = [
  {
    location: 'blocksuite/framework/global',
    name: '@blocksuite/global',
    workspaceDependencies: [],
  },
  {
    location: 'blocksuite/framework/std',
    name: '@blocksuite/std',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/store',
    ],
  },
  {
    location: 'blocksuite/framework/store',
    name: '@blocksuite/store',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/sync',
    ],
  },
  {
    location: 'blocksuite/framework/sync',
    name: '@blocksuite/sync',
    workspaceDependencies: ['blocksuite/framework/global'],
  },
  {
    location: 'blocksuite/integration-test',
    name: '@blocksuite/integration-test',
    workspaceDependencies: ['blocksuite/yunke/all', 'packages/theme'],
  },
  {
    location: 'blocksuite/playground',
    name: '@blocksuite/playground',
    workspaceDependencies: [
      'blocksuite/yunke/data-view',
      'blocksuite/integration-test',
      'blocksuite/yunke/all',
      'blocksuite/yunke/components',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
    ],
  },
  {
    location: 'blocksuite/yunke/all',
    name: '@blocksuite/yunke',
    workspaceDependencies: [
      'blocksuite/yunke/data-view',
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/framework/sync',
      'blocksuite/yunke/blocks/attachment',
      'blocksuite/yunke/blocks/bookmark',
      'blocksuite/yunke/blocks/callout',
      'blocksuite/yunke/blocks/code',
      'blocksuite/yunke/blocks/data-view',
      'blocksuite/yunke/blocks/database',
      'blocksuite/yunke/blocks/divider',
      'blocksuite/yunke/blocks/drawio',
      'blocksuite/yunke/blocks/edgeless-text',
      'blocksuite/yunke/blocks/embed',
      'blocksuite/yunke/blocks/embed-doc',
      'blocksuite/yunke/blocks/excalidraw',
      'blocksuite/yunke/blocks/flowchart',
      'blocksuite/yunke/blocks/frame',
      'blocksuite/yunke/blocks/image',
      'blocksuite/yunke/blocks/latex',
      'blocksuite/yunke/blocks/list',
      'blocksuite/yunke/blocks/mermaid',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/blocks/paragraph',
      'blocksuite/yunke/blocks/root',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/blocks/surface-ref',
      'blocksuite/yunke/blocks/table',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/foundation',
      'blocksuite/yunke/fragments/adapter-panel',
      'blocksuite/yunke/fragments/doc-title',
      'blocksuite/yunke/fragments/frame-panel',
      'blocksuite/yunke/fragments/outline',
      'blocksuite/yunke/gfx/brush',
      'blocksuite/yunke/gfx/connector',
      'blocksuite/yunke/gfx/group',
      'blocksuite/yunke/gfx/link',
      'blocksuite/yunke/gfx/mindmap',
      'blocksuite/yunke/gfx/note',
      'blocksuite/yunke/gfx/pointer',
      'blocksuite/yunke/gfx/shape',
      'blocksuite/yunke/gfx/template',
      'blocksuite/yunke/gfx/text',
      'blocksuite/yunke/gfx/turbo-renderer',
      'blocksuite/yunke/inlines/footnote',
      'blocksuite/yunke/inlines/latex',
      'blocksuite/yunke/inlines/link',
      'blocksuite/yunke/inlines/mention',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/drag-handle',
      'blocksuite/yunke/widgets/edgeless-auto-connect',
      'blocksuite/yunke/widgets/edgeless-dragging-area',
      'blocksuite/yunke/widgets/edgeless-selected-rect',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'blocksuite/yunke/widgets/edgeless-zoom-toolbar',
      'blocksuite/yunke/widgets/frame-title',
      'blocksuite/yunke/widgets/keyboard-toolbar',
      'blocksuite/yunke/widgets/linked-doc',
      'blocksuite/yunke/widgets/note-slicer',
      'blocksuite/yunke/widgets/page-dragging-area',
      'blocksuite/yunke/widgets/remote-selection',
      'blocksuite/yunke/widgets/scroll-anchoring',
      'blocksuite/yunke/widgets/slash-menu',
      'blocksuite/yunke/widgets/toolbar',
      'blocksuite/yunke/widgets/viewport-overlay',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/attachment',
    name: '@blocksuite/yunke-block-attachment',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/bookmark',
    name: '@blocksuite/yunke-block-bookmark',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/embed',
      'blocksuite/yunke/blocks/embed-doc',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/callout',
    name: '@blocksuite/yunke-block-callout',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/code',
    name: '@blocksuite/yunke-block-code',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/turbo-renderer',
      'blocksuite/yunke/inlines/latex',
      'blocksuite/yunke/inlines/link',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/data-view',
    name: '@blocksuite/yunke-block-data-view',
    workspaceDependencies: [
      'blocksuite/yunke/data-view',
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/database',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/database',
    name: '@blocksuite/yunke-block-database',
    workspaceDependencies: [
      'blocksuite/yunke/data-view',
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/drag-handle',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/divider',
    name: '@blocksuite/yunke-block-divider',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/drawio',
    name: '@blocksuite/yunke-block-drawio',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/edgeless-text',
    name: '@blocksuite/yunke-block-edgeless-text',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/text',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/embed',
    name: '@blocksuite/yunke-block-embed',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/pointer',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/embed-doc',
    name: '@blocksuite/yunke-block-embed-doc',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/embed',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/excalidraw',
    name: '@blocksuite/yunke-block-excalidraw',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/flowchart',
    name: '@blocksuite/yunke-block-flowchart',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/frame',
    name: '@blocksuite/yunke-block-frame',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/pointer',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'blocksuite/yunke/widgets/frame-title',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/image',
    name: '@blocksuite/yunke-block-image',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/turbo-renderer',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/latex',
    name: '@blocksuite/yunke-block-latex',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/latex',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/list',
    name: '@blocksuite/yunke-block-list',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/turbo-renderer',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/mermaid',
    name: '@blocksuite/yunke-block-mermaid',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/note',
    name: '@blocksuite/yunke-block-note',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/embed',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/fragments/doc-title',
      'blocksuite/yunke/gfx/turbo-renderer',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/paragraph',
    name: '@blocksuite/yunke-block-paragraph',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/turbo-renderer',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/root',
    name: '@blocksuite/yunke-block-root',
    workspaceDependencies: [
      'blocksuite/yunke/data-view',
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/attachment',
      'blocksuite/yunke/blocks/bookmark',
      'blocksuite/yunke/blocks/database',
      'blocksuite/yunke/blocks/edgeless-text',
      'blocksuite/yunke/blocks/embed',
      'blocksuite/yunke/blocks/frame',
      'blocksuite/yunke/blocks/image',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/blocks/paragraph',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/brush',
      'blocksuite/yunke/gfx/connector',
      'blocksuite/yunke/gfx/group',
      'blocksuite/yunke/gfx/mindmap',
      'blocksuite/yunke/gfx/note',
      'blocksuite/yunke/gfx/pointer',
      'blocksuite/yunke/gfx/shape',
      'blocksuite/yunke/gfx/text',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-selected-rect',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/surface',
    name: '@blocksuite/yunke-block-surface',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/surface-ref',
    name: '@blocksuite/yunke-block-surface-ref',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/frame',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/blocks/table',
    name: '@blocksuite/yunke-block-table',
    workspaceDependencies: [
      'blocksuite/yunke/data-view',
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/slash-menu',
    ],
  },
  {
    location: 'blocksuite/yunke/components',
    name: '@blocksuite/yunke-components',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/framework/sync',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/data-view',
    name: '@blocksuite/data-view',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/ext-loader',
    name: '@blocksuite/yunke-ext-loader',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/store',
    ],
  },
  {
    location: 'blocksuite/yunke/foundation',
    name: '@blocksuite/yunke-foundation',
    workspaceDependencies: [
      'blocksuite/yunke/data-view',
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/fragments/adapter-panel',
    name: '@blocksuite/yunke-fragment-adapter-panel',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/fragments/doc-title',
    name: '@blocksuite/yunke-fragment-doc-title',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/frame',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/fragments/frame-panel',
    name: '@blocksuite/yunke-fragment-frame-panel',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/frame',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/fragments/outline',
    name: '@blocksuite/yunke-fragment-outline',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/fragments/doc-title',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/brush',
    name: '@blocksuite/yunke-gfx-brush',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/connector',
    name: '@blocksuite/yunke-gfx-connector',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/text',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/group',
    name: '@blocksuite/yunke-gfx-group',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/text',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/link',
    name: '@blocksuite/yunke-gfx-link',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/bookmark',
      'blocksuite/yunke/blocks/embed',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/pointer',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/mindmap',
    name: '@blocksuite/yunke-gfx-mindmap',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/attachment',
      'blocksuite/yunke/blocks/edgeless-text',
      'blocksuite/yunke/blocks/image',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/connector',
      'blocksuite/yunke/gfx/pointer',
      'blocksuite/yunke/gfx/shape',
      'blocksuite/yunke/gfx/text',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/note',
    name: '@blocksuite/yunke-gfx-note',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/attachment',
      'blocksuite/yunke/blocks/bookmark',
      'blocksuite/yunke/blocks/image',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/pointer',
    name: '@blocksuite/yunke-gfx-pointer',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/shape',
    name: '@blocksuite/yunke-gfx-shape',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/text',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/template',
    name: '@blocksuite/yunke-gfx-template',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/text',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/text',
    name: '@blocksuite/yunke-gfx-text',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-toolbar',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/gfx/turbo-renderer',
    name: '@blocksuite/yunke-gfx-turbo-renderer',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
    ],
  },
  {
    location: 'blocksuite/yunke/inlines/footnote',
    name: '@blocksuite/yunke-inline-footnote',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/inlines/latex',
    name: '@blocksuite/yunke-inline-latex',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/inlines/link',
    name: '@blocksuite/yunke-inline-link',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/inlines/mention',
    name: '@blocksuite/yunke-inline-mention',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/inlines/preset',
    name: '@blocksuite/yunke-inline-preset',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/footnote',
      'blocksuite/yunke/inlines/latex',
      'blocksuite/yunke/inlines/link',
      'blocksuite/yunke/inlines/mention',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/inlines/reference',
    name: '@blocksuite/yunke-inline-reference',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/model',
    name: '@blocksuite/yunke-model',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/rich-text',
    name: '@blocksuite/yunke-rich-text',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/shared',
    name: '@blocksuite/yunke-shared',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/model',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/drag-handle',
    name: '@blocksuite/yunke-widget-drag-handle',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/callout',
      'blocksuite/yunke/blocks/embed',
      'blocksuite/yunke/blocks/list',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/blocks/paragraph',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/edgeless-auto-connect',
    name: '@blocksuite/yunke-widget-edgeless-auto-connect',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/edgeless-dragging-area',
    name: '@blocksuite/yunke-widget-edgeless-dragging-area',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/edgeless-selected-rect',
    name: '@blocksuite/yunke-widget-edgeless-selected-rect',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/blocks/frame',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/gfx/connector',
      'blocksuite/yunke/gfx/shape',
      'blocksuite/yunke/gfx/text',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/edgeless-toolbar',
    name: '@blocksuite/yunke-widget-edgeless-toolbar',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/edgeless-zoom-toolbar',
    name: '@blocksuite/yunke-widget-edgeless-zoom-toolbar',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/frame-title',
    name: '@blocksuite/yunke-widget-frame-title',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/keyboard-toolbar',
    name: '@blocksuite/yunke-widget-keyboard-toolbar',
    workspaceDependencies: [
      'blocksuite/yunke/data-view',
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/attachment',
      'blocksuite/yunke/blocks/database',
      'blocksuite/yunke/blocks/embed',
      'blocksuite/yunke/blocks/image',
      'blocksuite/yunke/blocks/latex',
      'blocksuite/yunke/blocks/list',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/blocks/paragraph',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/blocks/surface-ref',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/fragments/doc-title',
      'blocksuite/yunke/inlines/latex',
      'blocksuite/yunke/inlines/link',
      'blocksuite/yunke/inlines/preset',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/linked-doc',
    name: '@blocksuite/yunke-widget-linked-doc',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/blocks/image',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/inlines/reference',
      'blocksuite/yunke/model',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/note-slicer',
    name: '@blocksuite/yunke-widget-note-slicer',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/blocks/note',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'blocksuite/yunke/widgets/edgeless-selected-rect',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/page-dragging-area',
    name: '@blocksuite/yunke-widget-page-dragging-area',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/remote-selection',
    name: '@blocksuite/yunke-widget-remote-selection',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/scroll-anchoring',
    name: '@blocksuite/yunke-widget-scroll-anchoring',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/slash-menu',
    name: '@blocksuite/yunke-widget-slash-menu',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/framework/store',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/rich-text',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/toolbar',
    name: '@blocksuite/yunke-widget-toolbar',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/blocks/database',
      'blocksuite/yunke/blocks/surface',
      'blocksuite/yunke/blocks/table',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'blocksuite/yunke/widgets/viewport-overlay',
    name: '@blocksuite/yunke-widget-viewport-overlay',
    workspaceDependencies: [
      'blocksuite/framework/global',
      'blocksuite/framework/std',
      'blocksuite/yunke/components',
      'blocksuite/yunke/ext-loader',
      'blocksuite/yunke/model',
      'blocksuite/yunke/shared',
      'packages/theme',
    ],
  },
  {
    location: 'packages/common/auth',
    name: '@yunke/auth',
    workspaceDependencies: [],
  },
  {
    location: 'packages/common/config',
    name: '@yunke/config',
    workspaceDependencies: [],
  },
  {
    location: 'packages/common/debug',
    name: '@yunke/debug',
    workspaceDependencies: [],
  },
  {
    location: 'packages/common/env',
    name: '@yunke/env',
    workspaceDependencies: [],
  },
  {
    location: 'packages/common/error',
    name: '@yunke/error',
    workspaceDependencies: [],
  },
  {
    location: 'packages/common/infra',
    name: '@toeverything/infra',
    workspaceDependencies: [
      'packages/common/debug',
      'packages/common/env',
      'packages/common/error',
      'packages/frontend/templates',
    ],
  },
  {
    location: 'packages/common/nbstore',
    name: '@yunke/nbstore',
    workspaceDependencies: [
      'packages/common/infra',
      'packages/common/reader',
      'blocksuite/yunke/all',
      'packages/common/error',
    ],
  },
  {
    location: 'packages/common/reader',
    name: '@yunke/reader',
    workspaceDependencies: ['blocksuite/yunke/all'],
  },
  {
    location: 'packages/common/request',
    name: '@yunke/request',
    workspaceDependencies: ['packages/common/config'],
  },
  {
    location: 'packages/frontend/admin',
    name: '@yunke/admin',
    workspaceDependencies: [
      'packages/common/infra',
      'packages/theme',
      'packages/frontend/component',
      'packages/frontend/core',
      'packages/common/error',
      'packages/common/request',
      'packages/frontend/routes',
    ],
  },
  {
    location: 'packages/frontend/apps/android',
    name: '@yunke/android',
    workspaceDependencies: [
      'blocksuite/yunke/all',
      'packages/common/infra',
      'packages/frontend/component',
      'packages/frontend/core',
      'packages/common/env',
      'packages/frontend/i18n',
      'packages/common/nbstore',
      'tools/cli',
      'tools/utils',
    ],
  },
  {
    location: 'packages/frontend/apps/electron',
    name: '@yunke/electron',
    workspaceDependencies: [
      'packages/frontend/native-mock',
      'packages/common/infra',
      'tools/utils',
      'packages/common/nbstore',
    ],
  },
  {
    location: 'packages/frontend/apps/electron-renderer',
    name: '@yunke/electron-renderer',
    workspaceDependencies: [
      'blocksuite/yunke/all',
      'packages/common/infra',
      'packages/theme',
      'packages/frontend/component',
      'packages/frontend/core',
      'packages/common/debug',
      'packages/frontend/electron-api',
      'packages/frontend/i18n',
      'packages/common/nbstore',
      'packages/frontend/track',
      'tools/cli',
      'tools/utils',
    ],
  },
  {
    location: 'packages/frontend/apps/ios',
    name: '@yunke/ios',
    workspaceDependencies: [
      'blocksuite/yunke/all',
      'packages/common/infra',
      'packages/frontend/component',
      'packages/frontend/core',
      'packages/common/env',
      'packages/frontend/i18n',
      'packages/common/nbstore',
      'tools/cli',
      'tools/utils',
    ],
  },
  {
    location: 'packages/frontend/apps/mobile',
    name: '@yunke/mobile',
    workspaceDependencies: [
      'blocksuite/yunke/all',
      'packages/common/infra',
      'packages/frontend/component',
      'packages/frontend/core',
      'packages/common/env',
      'packages/frontend/i18n',
      'packages/common/nbstore',
    ],
  },
  {
    location: 'packages/frontend/apps/web',
    name: '@yunke/web',
    workspaceDependencies: [
      'packages/common/infra',
      'packages/frontend/component',
      'packages/frontend/core',
      'packages/common/env',
      'packages/frontend/i18n',
      'packages/common/nbstore',
      'packages/frontend/track',
    ],
  },
  {
    location: 'packages/frontend/apps/website',
    name: '@yunke/website',
    workspaceDependencies: [],
  },
  {
    location: 'packages/frontend/component',
    name: '@yunke/component',
    workspaceDependencies: [
      'packages/theme',
      'packages/common/debug',
      'packages/frontend/electron-api',
      'packages/common/error',
      'packages/frontend/i18n',
      'blocksuite/yunke/all',
      'tools/utils',
    ],
  },
  {
    location: 'packages/frontend/core',
    name: '@yunke/core',
    workspaceDependencies: [
      'blocksuite/framework/std',
      'blocksuite/yunke/all',
      'packages/common/infra',
      'packages/theme',
      'packages/frontend/component',
      'packages/common/debug',
      'packages/frontend/electron-api',
      'packages/common/env',
      'packages/common/error',
      'packages/frontend/i18n',
      'packages/common/nbstore',
      'packages/common/request',
      'packages/frontend/templates',
      'packages/frontend/track',
    ],
  },
  {
    location: 'packages/frontend/electron-api',
    name: '@yunke/electron-api',
    workspaceDependencies: ['packages/frontend/apps/electron'],
  },
  {
    location: 'packages/frontend/i18n',
    name: '@yunke/i18n',
    workspaceDependencies: [
      'packages/common/debug',
      'tools/cli',
      'tools/utils',
    ],
  },
  {
    location: 'packages/frontend/native-mock',
    name: '@yunke/native',
    workspaceDependencies: [],
  },
  {
    location: 'packages/frontend/routes',
    name: '@yunke/routes',
    workspaceDependencies: ['tools/cli', 'tools/utils'],
  },
  {
    location: 'packages/frontend/templates',
    name: '@yunke/templates',
    workspaceDependencies: [],
  },
  {
    location: 'packages/frontend/track',
    name: '@yunke/track',
    workspaceDependencies: ['packages/common/debug'],
  },
  {
    location: 'packages/theme',
    name: '@toeverything/theme',
    workspaceDependencies: [],
  },
  {
    location: 'tools/@types/build-config',
    name: '@types/build-config',
    workspaceDependencies: [],
  },
  {
    location: 'tools/@types/env',
    name: '@types/yunke__env',
    workspaceDependencies: ['blocksuite/yunke/all', 'packages/common/env'],
  },
  {
    location: 'tools/changelog',
    name: '@yunke/changelog',
    workspaceDependencies: [],
  },
  {
    location: 'tools/cli',
    name: '@yunke-tools/cli',
    workspaceDependencies: [
      'tools/utils',
      'packages/common/env',
      'packages/frontend/templates',
    ],
  },
  {
    location: 'tools/commitlint',
    name: '@yunke/commitlint-config',
    workspaceDependencies: [],
  },
  {
    location: 'tools/playstore-auto-bump',
    name: '@yunke/playstore-auto-bump',
    workspaceDependencies: ['tools/cli', 'tools/utils'],
  },
  {
    location: 'tools/utils',
    name: '@yunke-tools/utils',
    workspaceDependencies: [],
  },
];

export type PackageName =
  | '@blocksuite/global'
  | '@blocksuite/std'
  | '@blocksuite/store'
  | '@blocksuite/sync'
  | '@blocksuite/integration-test'
  | '@blocksuite/playground'
  | '@blocksuite/yunke'
  | '@blocksuite/yunke-block-attachment'
  | '@blocksuite/yunke-block-bookmark'
  | '@blocksuite/yunke-block-callout'
  | '@blocksuite/yunke-block-code'
  | '@blocksuite/yunke-block-data-view'
  | '@blocksuite/yunke-block-database'
  | '@blocksuite/yunke-block-divider'
  | '@blocksuite/yunke-block-drawio'
  | '@blocksuite/yunke-block-edgeless-text'
  | '@blocksuite/yunke-block-embed'
  | '@blocksuite/yunke-block-embed-doc'
  | '@blocksuite/yunke-block-excalidraw'
  | '@blocksuite/yunke-block-flowchart'
  | '@blocksuite/yunke-block-frame'
  | '@blocksuite/yunke-block-image'
  | '@blocksuite/yunke-block-latex'
  | '@blocksuite/yunke-block-list'
  | '@blocksuite/yunke-block-mermaid'
  | '@blocksuite/yunke-block-note'
  | '@blocksuite/yunke-block-paragraph'
  | '@blocksuite/yunke-block-root'
  | '@blocksuite/yunke-block-surface'
  | '@blocksuite/yunke-block-surface-ref'
  | '@blocksuite/yunke-block-table'
  | '@blocksuite/yunke-components'
  | '@blocksuite/data-view'
  | '@blocksuite/yunke-ext-loader'
  | '@blocksuite/yunke-foundation'
  | '@blocksuite/yunke-fragment-adapter-panel'
  | '@blocksuite/yunke-fragment-doc-title'
  | '@blocksuite/yunke-fragment-frame-panel'
  | '@blocksuite/yunke-fragment-outline'
  | '@blocksuite/yunke-gfx-brush'
  | '@blocksuite/yunke-gfx-connector'
  | '@blocksuite/yunke-gfx-group'
  | '@blocksuite/yunke-gfx-link'
  | '@blocksuite/yunke-gfx-mindmap'
  | '@blocksuite/yunke-gfx-note'
  | '@blocksuite/yunke-gfx-pointer'
  | '@blocksuite/yunke-gfx-shape'
  | '@blocksuite/yunke-gfx-template'
  | '@blocksuite/yunke-gfx-text'
  | '@blocksuite/yunke-gfx-turbo-renderer'
  | '@blocksuite/yunke-inline-footnote'
  | '@blocksuite/yunke-inline-latex'
  | '@blocksuite/yunke-inline-link'
  | '@blocksuite/yunke-inline-mention'
  | '@blocksuite/yunke-inline-preset'
  | '@blocksuite/yunke-inline-reference'
  | '@blocksuite/yunke-model'
  | '@blocksuite/yunke-rich-text'
  | '@blocksuite/yunke-shared'
  | '@blocksuite/yunke-widget-drag-handle'
  | '@blocksuite/yunke-widget-edgeless-auto-connect'
  | '@blocksuite/yunke-widget-edgeless-dragging-area'
  | '@blocksuite/yunke-widget-edgeless-selected-rect'
  | '@blocksuite/yunke-widget-edgeless-toolbar'
  | '@blocksuite/yunke-widget-edgeless-zoom-toolbar'
  | '@blocksuite/yunke-widget-frame-title'
  | '@blocksuite/yunke-widget-keyboard-toolbar'
  | '@blocksuite/yunke-widget-linked-doc'
  | '@blocksuite/yunke-widget-note-slicer'
  | '@blocksuite/yunke-widget-page-dragging-area'
  | '@blocksuite/yunke-widget-remote-selection'
  | '@blocksuite/yunke-widget-scroll-anchoring'
  | '@blocksuite/yunke-widget-slash-menu'
  | '@blocksuite/yunke-widget-toolbar'
  | '@blocksuite/yunke-widget-viewport-overlay'
  | '@yunke/auth'
  | '@yunke/config'
  | '@yunke/debug'
  | '@yunke/env'
  | '@yunke/error'
  | '@toeverything/infra'
  | '@yunke/nbstore'
  | '@yunke/reader'
  | '@yunke/request'
  | '@yunke/admin'
  | '@yunke/android'
  | '@yunke/electron'
  | '@yunke/electron-renderer'
  | '@yunke/ios'
  | '@yunke/mobile'
  | '@yunke/web'
  | '@yunke/website'
  | '@yunke/component'
  | '@yunke/core'
  | '@yunke/electron-api'
  | '@yunke/i18n'
  | '@yunke/native'
  | '@yunke/routes'
  | '@yunke/templates'
  | '@yunke/track'
  | '@toeverything/theme'
  | '@types/build-config'
  | '@types/yunke__env'
  | '@yunke/changelog'
  | '@yunke-tools/cli'
  | '@yunke/commitlint-config'
  | '@yunke/playstore-auto-bump'
  | '@yunke-tools/utils';
